/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    CustomDialog: typeof import('./src/components/Common/CustomDialog.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    GitNodesDialog: typeof import('./src/components/Dialog/GitNodesDialog.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InstallModelDialog: typeof import('./src/components/Dialog/InstallModelDialog.vue')['default']
    InstallNodesDialog: typeof import('./src/components/Dialog/InstallNodesDialog.vue')['default']
    ManagerButton: typeof import('./src/components/ManagerButton.vue')['default']
    ManagerDialog: typeof import('./src/components/Dialog/ManagerDialog.vue')['default']
    ManagerInstall: typeof import('./src/components/Dialog/ManagerDialogLeft/ManagerInstall.vue')['default']
    ManagerLeft: typeof import('./src/components/Dialog/ManagerDialogLeft/ManagerLeft.vue')['default']
    ManagerOthers: typeof import('./src/components/Dialog/ManagerDialogRight/ManagerOthers.vue')['default']
    ManagerRight: typeof import('./src/components/Dialog/ManagerDialogRight/ManagerRight.vue')['default']
    ManagerUpdate: typeof import('./src/components/Dialog/ManagerDialogLeft/ManagerUpdate.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    SnapshotDialog: typeof import('./src/components/Dialog/SnapshotDialog.vue')['default']
  }
}
